name: 'Release new version'

on:
  push:
    tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tagged version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'wristler.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig info.json'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "wristler.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true

      - name: Update info.json (Plugin version)
        uses: jossef/action-set-json-field@v2.1
        with:
          file: info.json
          field: version
          value: ${{ env.RELEASE_VERSION }}

      - name: Update info.json (Updated date)
        uses: jossef/action-set-json-field@v2.1
        with:
          file: info.json
          field: last_updated
          value: ${{ env.RELEASE_VERSION }}

      - name: Update info.json (Download URL)
        uses: jossef/action-set-json-field@v2.1
        with:
          file: info.json
          field: download_url
          value: "https://github.com/wristler/wristler-wordpress-plugin/releases/download/$RELEASE_VERSION/wristler.zip"

      - name: Update WordPress information
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          git commit -am "Updated WordPress information (info.json)"
          git push